Repository Sekanor/SM63PracticeHack, pull requests merged in 2020-11, with the labels that each got.

#26 Invalid commands
  src/classes/Code.as
  src/classes/CodeManager.as
  src/classes/Utils.as
Labels: improvement, infra

#20 Correctly established creyon codes
  docs/Commands.md
  src/classes/Overwrites.as
  src/classes/Utils.as
  src/classes/codes/CamLock.as
  src/classes/codes/Gravity.as
  src/classes/codes/Noclip.as
  src/classes/codes/ShowWarps.as
  src/classes/codes/Zoom.as
  src/classes/codes/ZoomLock.as
  src/frame3_1.as
Labels: new

#31 Help command / In-game documentation
  docs/Commands.md
  src/classes/Code.as
  src/classes/CodeManager.as
  src/classes/Event.as
  src/classes/TextManager.as
  src/classes/Utils.as
  src/classes/codes/BetaQuest.as
  src/classes/codes/BowserKey.as
  src/classes/codes/CamLock.as
  src/classes/codes/Cap.as
  src/classes/codes/Char.as
  src/classes/codes/ClearHotkey.as
  src/classes/codes/Coin.as
  src/classes/codes/Cutscenes.as
  src/classes/codes/Doorwarp.as
  src/classes/codes/FakeBowser.as
  src/classes/codes/File.as
  src/classes/codes/Fludd.as
  src/classes/codes/ForceWarp.as
  src/classes/codes/Gravity.as
  src/classes/codes/Health.as
  src/classes/codes/Help.as
  src/classes/codes/Hotkey.as
  src/classes/codes/IndividualLevel.as
  src/classes/codes/Kill.as
  src/classes/codes/Last.as
  src/classes/codes/LatestWarpPosition.as
  src/classes/codes/LevelName.as
  src/classes/codes/Lives.as
  src/classes/codes/LoadState.as
  src/classes/codes/Noclip.as
  src/classes/codes/Nozzle.as
  src/classes/codes/Position.as
  src/classes/codes/RedCoin.as
  src/classes/codes/RestartCoins.as
  src/classes/codes/SaveState.as
  src/classes/codes/SetPos.as
  src/classes/codes/ShowWarps.as
  src/classes/codes/Silver.as
  src/classes/codes/Star.as
  src/classes/codes/StarCoin.as
  src/classes/codes/Timer.as
  src/classes/codes/Warp.as
  src/classes/codes/Water.as
  src/classes/codes/Zoom.as
  src/classes/codes/ZoomLock.as
Labels: new

#34 Resetroom command
  docs/Commands.md
  src/classes/Utils.as
  src/classes/codes/ResetRoom.as
Labels: new

#37 ShowCollision working
  docs/Commands.md
  src/classes/Utils.as
  src/classes/codes/ShowCollision.as
Labels: improvement

#40 Memory watch
  docs/Commands.md
  src/DefineEditText642.txt
  src/classes/Event.as
  src/classes/Main.as
  src/classes/MemoryWatch.as
  src/classes/TextManager.as
  src/classes/codes/WatchVar.as
Labels: new

#42 Warp system improvement
  src/_generator.py
  src/classes/BetaQuest.as
  src/classes/Utils.as
  src/classes/World.as
  src/classes/worlds/WorldB1Reds.as
  src/classes/worlds/WorldB2Reds.as
  src/classes/worlds/WorldB3Reds.as
  src/classes/worlds/WorldBM.as
  src/classes/worlds/WorldBoB.as
  src/classes/worlds/WorldBowser1.as
  src/classes/worlds/WorldBowser2.as
  src/classes/worlds/WorldBowser3.as
  src/classes/worlds/WorldCastle.as
  src/classes/worlds/WorldCoE.as
  src/classes/worlds/WorldEndgame.as
  src/classes/worlds/WorldEotMK.as
  src/classes/worlds/WorldEscape.as
  src/classes/worlds/WorldFF.as
  src/classes/worlds/WorldGoS.as
  src/classes/worlds/WorldGreenShine.as
  src/classes/worlds/WorldHMC.as
  src/classes/worlds/WorldJRB.as
  src/classes/worlds/WorldLLL.as
  src/classes/worlds/WorldLevel1.as
  src/classes/worlds/WorldMM.as
  src/classes/worlds/WorldRR.as
  src/classes/worlds/WorldRedShine.as
  src/classes/worlds/WorldSL.as
  src/classes/worlds/WorldSSL.as
  src/classes/worlds/WorldSotM.as
  src/classes/worlds/WorldSotS.as
  src/classes/worlds/WorldSpace.as
  src/classes/worlds/WorldTTC.as
  src/classes/worlds/WorldTTM.as
  src/classes/worlds/WorldThwC.as
  src/classes/worlds/WorldTidal.as
  src/classes/worlds/WorldTutorial1.as
  src/classes/worlds/WorldTutorial2.as
  src/classes/worlds/WorldWDW.as
Labels: improvement, infra

#41 Beta Quest bug fixing #1
  docs/Commands.md
  src/classes/BetaQuest.as
  src/classes/Event.as
  src/classes/Utils.as
  src/classes/codes/Animation.as
  src/classes/codes/BetaQuest.as
  src/classes/codes/File.as
  src/classes/worlds/WorldMM.as
Labels: bug

#59 WarpList command
  docs/Commands.md
  src/classes/Utils.as
  src/classes/codes/WarpList.as
Labels: new

#61 Fix warping to an undefined location
  src/classes/Utils.as
  src/classes/codes/Warp.as
  src/classes/worlds/WorldEotMK.as
Labels: bug
